### ISSUE TITLE
V3 release checklist

### ISSUE THREAD

**Issue by cal-smith** [IBM/carbon-components-angular#499]
- [x] PR freeze
- [x] #459 merged into breaking-changes
- [x] `BREAKING CHANGES` commit merged to breaking-changes
- [x] v9 branch updated with master
  - [x] v9 branch release config updated with `2.X` range
- [x] breaking-changes merged into master
  - [x] v3 published
- [x] party 🎉
