### ISSUE TITLE
Documentation improvement tracking

### ISSUE THREAD

**Issue by cal-smith** [IBM/carbon-components-angular#673]
Issue to track improvements that can be made to the documentation

- [ ] TableModel headers and columns must be equal length (otherwise unexpected behavior occurs)
- [ ] upgrade guides should be visibly linked in more places
- [ ] dropdown appendInline/ToBody behavior and examples
- [ ] icons-angular usage (link out to that readme)
- [ ] tooltip placement and control
- [ ] completely custom tooltip examples
- [ ] custom modal usage patterns
- [ ] state management with tabs (active tabs, saving-restoring state, generating tabs)
- [ ] forms and modals
- [ ] UI Shell ... just all of it
- [ ] boolean attribute weirdness (`[expanded]="false"` isn't the same as `expanded="false"`)
- [ ] complex layouts with grid and components like Tile
- [ ] accessible tabs
- [ ] accessible form controls
- [ ] time picker usage patterns (single, multiple, ngModel, etc)
- [ ] date picker patterns (single, multiple, ngModel, etc)
- [ ] Observable items in dropdowns (and patterns around updating dropdown items)
- [ ] patterns around searching (handling `enter`, ngModel/valueChange, clearing, etc)
- [ ] modal sizing
- [ ] tabs as navigation
- [ ] pagination + table + header patterns

**Comment by cal-smith** [comment]
- [ ] template driven forms patterns
- [ ] reactive forms patterns
- [ ] style override patterns
- [ ] complex radio examples
